{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.applicationName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.applicationName | quote }}
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: {{ printf "%s/backend-application" (.Values.externalSecrets.pathPrefix | default .Release.Namespace) | quote }}
{{- end }}
