apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
resources:
- namespace.yaml
- vault
- platform
- storageclass.yaml
- postgres-config.yaml
- backend-config.yaml
- frontend-nginx.yaml
- external-secrets
- letsencrypt-production.yaml
- svc-postgres.yaml
- svc-postgres-headless.yaml
- svc-mailpit.yaml
- postgres.yaml
- mailpit.yaml
- certificate.yaml
- backend.yaml
- frontend.yaml
- cluster-domain-claim.yaml
- domain-mapping.yaml
