apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-cert-manager
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: cert-manager/cloudflare-api-token-secret
