apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banco-srjm-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srjm23/Banco-srjm-k8s.git
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
