apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://srjm23.github.io/Banco-srjm-k8s/
    targetRevision: 1.0.0
    helm:
      releaseName: backend
    chart: banco-srjm-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: banco-srjm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
