apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://srjm23.github.io/Banco-srjm-k8s/
    targetRevision: 1.0.0
    helm:
      releaseName: frontend
    chart: banco-srjm-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: banco-srjm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
