apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: postgres
  ports:
  - name: tcp-postgres
    port: 5432
    targetPort: tcp-postgres
