apiVersion: v1
kind: Secret
metadata:
  name: backend-application
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  application.yaml: |
{{ .Files.Get "files/application.yaml" | indent 4 }}
