{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backendName | quote }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_URL: {{ default (printf "jdbc:postgresql://postgres:5432/%s" .Values.postgres.database) .Values.secrets.databaseUrl | quote }}
  MAIL_USERNAME: {{ .Values.secrets.mailUsername | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | quote }}
  DATA_ENCRYPTION_KEY: {{ required "Informe secrets.dataEncryptionKey" .Values.secrets.dataEncryptionKey | quote }}
  ADMINISTRATOR_CREATION_TOKEN: {{ required "Informe secrets.administratorCreationToken" .Values.secrets.administratorCreationToken | quote }}
{{ end }}
