{{ if and .Values.knative.enabled .Values.knative.createDomainClaim }}
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: {{ .Values.istio.host | quote }}
spec:
  namespace: {{ .Release.Namespace }}
{{ end }}
