{{ if not .Values.knative.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.istio.enabled | quote }}
        checksum/runtime: {{ include "banco-srjm.checksum.runtime" . }}
        checksum/config: {{ include "banco-srjm.checksum.config" . }}
        checksum/secrets: {{ include "banco-srjm.checksum.secrets" . }}
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx
      containers:
      - name: frontend
        image: {{ printf "%s:%s" .Values.frontend.image.repository .Values.frontend.image.tag | quote }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
        resources: {{ .Values.frontend.resources | toJson }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx-main.conf
          readOnly: true
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
      imagePullSecrets: {{ .Values.imagePullSecrets | toJson }}
{{ end }}
