{{ if and .Values.istio.enabled (not .Values.knative.enabled) }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: banco-srjm
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.istio.host | quote }}
  gateways:
    - {{ printf "%s/%s" .Values.istio.gateway.namespace .Values.istio.gateway.name | quote }}
  http:
    - route:
        - destination:
            host: {{ printf "frontend.%s.svc.cluster.local" .Release.Namespace }}
            port:
              number: 8080
{{ end }}
