{{ if and .Values.istio.enabled (not .Values.knative.enabled) .Values.istio.gateway.create }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Values.istio.gateway.namespace }}
spec:
  selector: {{ .Values.istio.gateway.selector | toJson }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host | quote }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.istio.host | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.gateway.tlsCredentialName | quote }}
{{ end }}
