{{ if .Values.knative.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.knative.dev/ingress-class: {{ .Values.knative.ingressClass | quote }}
spec:
  {{- with .Values.knative.frontend.traffic }}
  traffic: {{ . | toJson }}
  {{- end }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
        autoscaling.knative.dev/min-scale: {{ .Values.knative.frontend.minScale | quote }}
        autoscaling.knative.dev/max-scale: {{ .Values.knative.frontend.maxScale | quote }}
        checksum/runtime: {{ include "banco-srjm.checksum.runtime" . }}
        checksum/config: {{ include "banco-srjm.checksum.config" . }}
        checksum/secrets: {{ include "banco-srjm.checksum.secrets" . }}
    spec:
      containers:
      - image: {{ printf "%s:%s" .Values.frontend.image.repository .Values.frontend.image.tag | quote }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        name: frontend
        ports:
        - containerPort: 8080
          name: http1
        readinessProbe:
          httpGet:
            path: /healthz
          periodSeconds: 10
        resources: {{ .Values.frontend.resources | toJson }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/banco-nginx
          readOnly: true
        command:
        - nginx
        args:
        - -c
        - /etc/banco-nginx/nginx-main.conf
        - -g
        - daemon off;
      volumes:
      - configMap:
          name: frontend-nginx
        name: nginx-config
      imagePullSecrets: {{ .Values.imagePullSecrets | toJson }}
      containerConcurrency: {{ .Values.knative.frontend.containerConcurrency }}
      timeoutSeconds: {{ .Values.knative.timeoutSeconds }}
{{ end }}
