{{ if .Values.knative.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    networking.knative.dev/ingress-class: {{ .Values.knative.ingressClass | quote }}
spec:
  {{- with .Values.knative.backend.traffic }}
  traffic: {{ . | toJson }}
  {{- end }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
        autoscaling.knative.dev/min-scale: {{ .Values.knative.backend.minScale | quote }}
        autoscaling.knative.dev/max-scale: {{ .Values.knative.backend.maxScale | quote }}
        checksum/runtime: {{ include "banco-srjm.checksum.runtime" . }}
        checksum/config: {{ include "banco-srjm.checksum.config" . }}
        checksum/secrets: {{ include "banco-srjm.checksum.secrets" . }}
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.backendName | quote }}
              key: DB_URL
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ .Values.secrets.postgresName | quote }}
        - name: SPRING_FLYWAY_CONNECT_RETRIES
          value: {{ .Values.knative.flywayConnectRetries | quote }}
        - name: SERVER_PORT
          value: '8080'
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: {{ .Values.secrets.backendName | quote }}
        image: {{ printf "%s:%s" .Values.backend.image.repository .Values.backend.image.tag | quote }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/actuator/health/liveness
          periodSeconds: 10
          timeoutSeconds: 3
          initialDelaySeconds: 300
        name: backend
        ports:
        - containerPort: 8080
          name: http1
        readinessProbe:
          httpGet:
            path: /api/actuator/health/readiness
          periodSeconds: 10
          timeoutSeconds: 3
        resources: {{ .Values.backend.resources | toJson }}
        volumeMounts:
        - mountPath: /etc/banco
          name: application-config
          readOnly: true
      volumes:
      - secret:
          secretName: backend-application
        name: application-config
      imagePullSecrets: {{ .Values.imagePullSecrets | toJson }}
      containerConcurrency: {{ .Values.knative.backend.containerConcurrency }}
      timeoutSeconds: {{ .Values.knative.timeoutSeconds }}
{{ end }}
