{{ if .Values.mailpit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.mailpit.replicas }}
  selector:
    matchLabels:
      app: mailpit
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mailpit
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: {{ and .Values.istio.enabled (not .Values.knative.enabled) | quote }}
        checksum/config: {{ include "banco-srjm.checksum.config" . }}
        checksum/secrets: {{ include "banco-srjm.checksum.secrets" . }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mailpit
        image: {{ printf "%s:%s" .Values.mailpit.image.repository .Values.mailpit.image.tag | quote }}
        imagePullPolicy: {{ .Values.mailpit.image.pullPolicy }}
        ports:
        - name: tcp-smtp
          containerPort: 1025
        - name: http
          containerPort: 8025
        resources: {{ .Values.mailpit.resources | toJson }}
        readinessProbe:
          tcpSocket:
            port: 8025
          periodSeconds: 10
      imagePullSecrets: {{ .Values.imagePullSecrets | toJson }}
{{ end }}
