{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgresName | quote }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "Informe secrets.postgresPassword" .Values.secrets.postgresPassword | quote }}
{{ end }}
