knative:
  enabled: true
  frontend:
    minScale: 1
    maxScale: 3
  backend:
    minScale: 1
    maxScale: 3
istio:
  host: bancosrjm.geradorqrcode-srjm.uk
certManager:
  enabled: true
  createIssuer: false
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  email: srjm99silva@gmail.com
