apiVersion: v1
kind: Service
metadata:
  name: istio-ingress-classic
  namespace: istio-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 'false'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: istio-ingress
    istio: ingress
  ports:
  - name: http2
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
